version: "3"

services:
  #SERVER --------------------------------------//
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - PORT=${SERVER_PORT}
      - NODE_ENV=${NODE_ENV}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server/src:/app/server/src
    restart: always

  #CLIENT --------------------------------------//
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    links:
      - server
    depends_on:
      - server
    restart: always
